INPUTS:
  - token: "value"
    customStatus: true  # / false 
    voiceEnabled: true  # / false
    activity:
      type: "STREAMING" # STREAMING, PLAYING, LISTENING, WATCHING, COMPETING

  - token: "value 2"
    customStatus: false  # / true 
    voiceEnabled: false  # / true
    activity:
      type: "LISTENING" # STREAMING, PLAYING, LISTENING, WATCHING, COMPETING

OPTIONS:
  location: "Bangkok" # default
  tz: "Asia/Bangkok" # default

VOICE:
  data: "sx!" # Default | join sx!join <vcid> - leave sx!leave

STATUS:
  delay: 4000 # default (Minimum 4000)
  data:
    - emoji: "üß°"
      text: "TEXT 1"
    - emoji: "üíõ"
      text: "TEXT 2"
    - emoji: "üíö"
      text: "TEXT 3"
    - emoji: "üíô"
      text: "TEXT 4"
    - emoji: "üíú"
      text: "TEXT 5"

RPC:
  delay: 4000 # default (Minimum 4000)

  # this for type listening only
  timestamp:
      #start: "2025-09-02T07:45:34.593Z" # ISO8601 | timestamp in milliseconds
      #end: "2029-12-31T17:00:00.000Z" # ISO8601 | timestamp in milliseconds

  TwitchURL: "https://www.twitch.tv/4levy_z1"
  # YoutubeURL: "https://www.youtube.com/@4levy"

  details:
    - " ‡≠®‡≠ßÔø§ {time:en:12} : ìÜ© ‡≥Ä ìÜ™ {en=year:2} "
  state:
    - "Íí∞‡¶å Íí∞ À∂>‚∏ù‚∏ù‚∏ù<Àµ ‡æÄ‡Ω≤Íí± ‡ªíÍí±"
  assetsLargeText:
    - "0nyx"
  assetsSmallText:
    - "‡¨òÍí∞‡æÄ‡Ω≤^ Àï ‡∫¥^  ‡æÄ‡Ω≤Íí±"
  assetsLargeImage:
    - "https://i.postimg.cc/DzRFzTV6/angel_angelcore_aesthetic_fantasy_creatures_fantasy.jpg"
  assetsSmallImage:
    - "https://i.pinimg.com/1200x/e6/b4/a7/e6b4a73f43ab3fdaed7c6af5b814dedd.jpg"
  buttonFirst:
    - label: "> Bio <"
      url: "https://0nyx-wha.vercel.app/"
  buttonSecond:
    - label: "[ Server ]"
      url: "https://discord.gg/pQVtDP8GEE"